### ISSUE TITLE
Liquibase doesn't seem to run with a hibernate gorm datasource

### ISSUE THREAD

**Issue by jisikoff** [micronaut-projects/micronaut-liquibase#18] opened 2019-04-17 14:11 UTC
With a hibernate gorm setup in micronaut like this:
```
dataSource:
  url: ...
  pooled: true
  jmxExport: true
  driverClassName: 
  username:
  password: 

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/changelog-master.groovy'
```

the liquibase runner seems to not run because it doesn't get past this line in LiquibaseMigrationRunner:
```
     if (event.getBeanDefinition() instanceof NameResolver) {
```

**Comment by ilopmar** [comment] 2020-02-19 07:37
There is no support for GORM at this moment. Take a look at https://github.com/micronaut-projects/micronaut-liquibase/issues/6

**Comment by jameskleeh** [comment] 2020-02-19 20:21
Duplicate of #6

**Closed by jameskleeh** 2020-02-19 20:21 UTC
